baseURL: https://niortweb.fr
languageCode: fr-FR
title: NiortWeb, meetup collaboratif
theme: niortweb
# theme: ../..

# Option to specify the default language of the theme
# I.e., the landing language of your root 
DefaultContentLanguage: fr

## Option to disable additional language in your site.
# disableLanguages: ["ru"]

disableKinds: ["sitemap","RSS"]

# Option to specify that all links will be open in a new tab.
blackfriday:
  hrefTargetBlank: true

Taxonomies:
  tag: "tags"

# Supported fonts are:
# https://fonts.google.com/

# Icons taken from:
# https://konpa.github.io/devicon/
# https://bulkitv2.cssninja.io/_components-icons-fa.html

params:
  maxPlaces: 20
  myApi: https://niortweb.fr/
  #myApi: http://localhost:5001/niortweb/us-central1/api/
  

  registerFormUrl: https://app.niortweb.fr
  #registerFormUrl: /inscription
  # https://www.epochconverter.com/ 
  # 11/01/21 si valorisé, alors le bouton HOME est visible
  meetupTs: 1623148200
  
  
  
  meetupId: QUEST_CE_QUE_IA_160221
  meetupTitle: Qu’est-ce que l’IA ? Par où commencer ?
  meetupSpeaker: Quentin NICOLLE
  meetupWebconf: 1
  # https://jennamolby.com/tools/google-calendar-link-generator/
  meetupGgCalendarLink: http://www.google.com/calendar/event?action=TEMPLATE&dates=20210216T113000Z%2F20210216T123000Z&text=Qu%E2%80%99est-ce%20qu%E2%80%99IA%20%3F%20Par%20o%C3%B9%20commencer%20%3F&location=https%3A%2F%2Fniortweb.fr%2Fapi%2Fmeetup%2FQUEST_CE_QUE_IA_160221%2Fwebconf&details=L%E2%80%99intelligence%20artificelle%20(ou%20IA%20pour%20les%20intimes)%20est%20bien%20grand%20mot%20qui%20cache%20plein%20de%20myst%C3%A8res.%0A%0AEnsemble%20nous%20allons%20ouvrir%20cette%20boite%20noire%20pour%20y%20d%C3%A9couvrir%20ce%20monde%20merveilleux%20aux%20perspectives%20casi%20infinies.%0A%0AAu%20programme%20de%20se%20talk%20%3A%0A%0ANous%20allons%20donner%20une%20d%C3%A9finition%20%C3%A0%20l%E2%80%99intelligence%20artificielle%0AD%C3%A9couvrir%20quel%20lien%20elle%20entretien%20avec%20le%20domaine%20de%20la%20data%20science%0AVoir%20que%2C%20comme%20dans%20l%E2%80%99esp%C3%A8re%20humaine%2C%20l%E2%80%99intelligence%20peut%20se%20pr%C3%A9senter%20sous%20plusieurs%20formes.%0AEn%202021%2C%20la%20mise%20en%20place%20d%E2%80%99une%20intelligence%20artificielle%20associ%C3%A9%20%C3%A0%20un%20domaine%20ou%20un%20besoin%20se%20d%C3%A9mocratise%20grandement.%20Nous%20ferons%20aussi%20le%20tour%20de%20quelques%20pr%C3%A9requis%20et%2Fou%20outils%20pour%20commencer%20%C3%A0%20impl%C3%A9menter%20nos%20propres%20intelligences.%0A%0AAnim%C3%A9%20par%20Quentin%20NICOLLE

  description: NiortWeb est un meetup collaboratif Niortais pour faciliter le partage et l'accès aux expériences de chacun sur des sujets Web. Si tu as envie de progresser ou de partager ton expérience informatique ? Tu es développeur, concepteur, architecte, passionné, ergonome, ux designer ou simplement intéressé par les sujets. Ce MeetUp est fait pour toi, c'est un moment décontracté en présentiel ou à distance autour de thématiques web.
  
  newsletterForm: https://forms.gle/bKSgFf8KfaQTLtJV9
  # parameter used to specify if you want to minify the imported js
  jsMinify: false
  # parameter used to specify if you want to add the fingerprint to the imported js
  jsFingerprint: false
  # parameter used to specify if you want to minify the imported css
  cssMinify: true
  # parameter used to specify if you want to add the fingerprint to the imported css
  cssFingerprint: true
  # option to specify the main colour of the theme
  mainColour: "#00b7ffff"

  #voteUrl: https://forms.gle/6LsNdPkgKCHMtsYb9 

  # summary options
  summary:
    # option to specify the default image in the summary list
    defaultImage : "/images/default_summary.jpg"
  
  # loading options
  loading:
    # option to specify the loading image
    image: "/images/loaders/rings.svg"

  # main pages options
  mainPage:
    # option to specify the main font of the theme
    fontFamily: "Open Sans" 

  # sidebar options
  sidebar:
    # option to specify the logo of the sidebar
    logo: "/images/sidebar.svg"
    # option to specify the font of the sidebar
    fontFamily: "Open Sans" # "Open Sans"

  # navbar options
  navbar:
    # option to specify the logo of the sidebar
    fontFamily: "Open Sans"
  
  # 404 page options
  pagNotFound:
    # option to specify the main picture of the sidebar
    image: "/images/404-page-04.png"
    # option to specify the title of the 404 page
    title: 404 page introuvable :(
    # option to specify the subtitle of the 404 page
    subtitle: La page demandée n'existe pas ou plus...
    # option to specify the width of the image in the 404 page
    imageWidth: 500px  

  # 404 page options
  pagErr:
    # option to specify the main picture of the sidebar
    image: "/images/404-page-04.png"
    # option to specify the title of the 404 page
    title: Une erreur est survenue :(
    # option to specify the subtitle of the 404 page
    subtitle: Veuillez revenir un peu plus tard...
    # option to specify the width of the image in the 404 page
    imageWidth: 500px  

  news:
    #title: /!\ Prochaine date le 04/05
    description: En ligne + NiortTech à 12h30, inscrivez-vous ;-)

  # homepage options
  homepage:
    # option to specify the title in the homepage
    title: NiortWeb, meetup collaboratif
    # option to specify the subtitle in the homepage
    
    #subtitle: Envie de progresser ou de partager ton expérience informatique ? Rejoins-nous !
    subtitle: Envie de progresser ou de partager ton expérience informatique ?  Rejoins-nous le 08/06 sur "La qualité de code" !

    # option to specify image in the homepage
    image: "/images/home.png" # worker.svg 
    # option to specify the width of the image in the homepage
    imageWidth: 500px

  # footer options
  footer:
    # option to specify the logo in the footer
    logo: "/images/footer.png"
    # option to specify your contact email in the footer
    email: ff.fremont.florent@gmail.com
    # option to specify your linkedin profile in the footer
    # linkedin: https://www.linkedin.com/florent-fremont-b2a943a9/
    # option to specify your facebook account in the footer; **uncomment** the below line to show in footer
    # facebook: your.username
    # option to specify your github account in the footer; **uncomment** the below line to show in footer
    github: ffremont
    slack: https://join.slack.com/t/niortweb/shared_invite/zt-j5dsxq3b-iQK~NE09Sxp4POn2CgDWqA
    # option to specify your twitter username in the footer; **uncomment** the below line to show in footer
    #twitter: ff_florent
    # option to specify your instagram username in the footer; **uncomment** the below line to show in footer
    # instagram: username
    # option to specify the copyright in the footer
    # copyright: NiortWeb - 2019

# multilanguage support
languages:
  en:
    languageName:       English
    weight:             2
  fr:
    languageName:       French
    weight:             1